steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - 'build'
      - '-t'
      - 'northamerica-northeast2-docker.pkg.dev/gcp-class-16/aman-bank-repo/bank-frontend'
      - '--build-arg' 
      - 'REACT_APP_API_URL=https://aman-bank-backend-79505229087.northamerica-northeast2.run.app'
      - '.'
    dir: 'bank-frontend'

  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      - 'push'
      - 'northamerica-northeast2-docker.pkg.dev/gcp-class-16/aman-bank-repo/bank-frontend'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Deploy
    entrypoint: gcloud
    args:
      - run
      - deploy
      - aman-bank-frontend
      - --image=northamerica-northeast2-docker.pkg.dev/gcp-class-16/aman-bank-repo/bank-frontend
      - --region=northamerica-northeast2
      - --platform=managed
      - --allow-unauthenticated

options:
  logging: CLOUD_LOGGING_ONLY
